<option value="ABAR FORD">ABAR FORD</option>
<option value="ACE">ACE</option>
<option value="ADTEC">ADTEC</option>
<option value="AM TRAILER">AM TRAILER</option>
<option value="AMG TRUCK">AMG TRUCK</option>
<option value="APACHE">APACHE</option>
<option value="ASHOCK LEYLAND">ASHOCK LEYLAND</option>
<option value="ATOMIK">ATOMIK</option>
<option value="AVIC">AVIC</option>
<option value="Acura">Acura</option>
<option value="Adly">Adly</option>
<option value="Aixam">Aixam</option>
<option value="Alfa Romeo">Alfa Romeo</option>
<option value="Alpina">Alpina</option>
<option value="Alvis">Alvis</option>
<option value="Aprilias">Aprilias</option>
<option value="Aston Martin">Aston Martin</option>
<option value="Audi">Audi</option>
<option value="Austin">Austin</option>
<option value="Austin-Healey">Austin-Healey</option>
<option value="Auto Union">Auto Union</option>
<option value="Autobianchi">Autobianchi</option>
<option value="Auverland">Auverland</option>
<option value="BAJAJ">BAJAJ</option>
<option value="BEI BEN">BEI BEN</option>
<option value="BEIFANG">BEIFANG</option>
<option value="BHACHU">BHACHU</option>
<option value="BMW">BMW</option>
<option value="BOMAG 80">BOMAG 80</option>
<option value="BPW">BPW</option>
<option value="BROSHUIS">BROSHUIS</option>
<option value="Barkas">Barkas</option>
<option value="Bedford">Bedford</option>
<option value="Benelli">Benelli</option>
<option value="Bentley">Bentley</option>
<option value="Bertone">Bertone</option>
<option value="Beta">Beta</option>
<option value="Bio Auto">Bio Auto</option>
<option value="Bitter">Bitter</option>
<option value="Bluecar">Bluecar</option>
<option value="Bond">Bond</option>
<option value="Borgward">Borgward</option>
<option value="braaap">Braaap</option>
<option value="Bristol">Bristol</option>
<option value="Bugatti">Bugatti</option>
<option value="Buick">Buick</option>
<option value="CA1041">CA1041</option>
<option value="CAPTAIN">CAPTAIN</option>
<option value="CASE TRACTORS">CASE TRACTORS</option>
<option value="CATEPILAR">CATEPILAR</option>
<option value="CFMoto">CFMoto</option>
<option value="CMC TRAILER">CMC TRAILER</option>
<option value="COMMUTER">COMMUTER</option>
<option value="COMPTON">COMPTON</option>
<option value="Cadillac">Cadillac</option>
<option value="Callaway">Callaway</option>
<option value="Can-Am">Can-Am</option>
<option value="Carbodies">Carbodies</option>
<option value="Casalini">Casalini</option>
<option value="Caterham">Caterham</option>
<option value="Checker">Checker</option>
<option value="Chery">Chery</option>
<option value="Chevrolet">Chevrolet</option>
<option value="Chrysler">Chrysler</option>
<option value="CitroÃ«n">CitroÃ«n</option>
<option value="DAF">DAF</option>
<option value="DAYUN">DAYUN</option>
<option value="DENNISON">DENNISON</option>
<option value="DOLL">DOLL</option>
<option value="DOOSAN">DOOSAN</option>
<option value="DS">DS</option>
<option value="Dacia">Dacia</option>
<option value="Daewoo">Daewoo</option>
<option value="Daihatsu">Daihatsu</option>
<option value="Daimler">Daimler</option>
<option value="De La Chapelle">De La Chapelle</option>
<option value="De Lorean">De Lorean</option>
<option value="De Tomaso">De Tomaso</option>
<option value="Dodge"></option>
<option value="Dongfeng Sokon (DFSK)">Dongfeng Sokon (DFSK)</option>
<option value="Donkervoort">Donkervoort</option>
<option value="Ducati">Ducati</option>
<option value="EICHER">EICHER</option>
<option value="ELITE">ELITE</option>
<option value="EVALAST KUGA 150">EVALAST KUGA 150</option>
<option value="Ebro">Ebro</option>
<option value="Effedi">Effedi</option>
<option value="Elstar">Elstar</option>
<option value="FAW">FAW</option>
<option value="FLYBOY">FLYBOY</option>
<option value="FOCIN">FOCIN</option>
<option value="FODEN">FODEN</option>
<option value="FRUEHAUF">FRUEHAUF</option>
<option value="Ferrari">Ferrari</option>
<option value="Fiat">Fiat</option>
<option value="Fonzarelli">Fonzarelli</option>
<option value="Ford">Ford</option>
<option value="Foton">Foton</option>
<option value="Freightliner">Freightliner</option>
<option value="GMC">GMC</option>
<option value="GREAT WALL">GREAT WALL</option>
<option value="Gas Gas">Gas Gas</option>
<option value="Geely">Geely</option>
<option value="Geo">Geo</option>
<option value="German E-Cars">German E-Cars</option>
<option value="Ginetta">Ginetta</option>
<option value="Glas">Glas</option>
<option value="Golden Dragon">Golden Dragon</option>
<option value="Grecav">Grecav</option>
<option value="Groz">Groz</option>
<option value="HAMM">HAMM</option>
<option value="HANS">HANS</option>
<option value="HAOJIN">HAOJIN</option>
<option value="HAWK">HAWK</option>
<option value="HERO">HERO</option>
<option value="HINO">HINO</option>
<option value="HOWO">HOWO</option>
<option value="HUILI">HUILI</option>
<option value="Harley-Davidson">Harley-Davidson</option>
<option value="Hillman">Hillman</option>
<option value="Hindustan">Hindustan</option>
<option value="Hisun">Hisun</option>
<option value="Holden">Holden</option>
<option value="Honda">Honda</option>
<option value="Hummer">Hummer</option>
<option value="Husqvarna">Husqvarna</option>
<option value="Hyosung">Hyosung</option>
<option value="Hyundai">Hyundai</option>
<option value="IKONIK">IKONIK</option>
<option value="INTERNATIONAL">INTERNATIONAL</option>
<option value="IZH">IZH</option>
<option value="Indian">Indian</option>
<option value="Infiniti">Infiniti</option>
<option value="Innocenti">Innocenti</option>
<option value="Irmscher">Irmscher</option>
<option value="Isdera">Isdera</option>
<option value="Isuzu">Isuzu</option>
<option value="Iveco">Iveco</option>
<option value="JAC">JAC</option>
<option value="JCB">JCB</option>
<option value="JINCHENG">JINCHENG</option>
<option value="JMC BOARDING JX1022">JMC BOARDING JX1022</option>
<option value="JOHN DEERE">JOHN DEERE</option>
<option value="Jaguar">Jaguar</option>
<option value="Jeep">Jeep</option>
<option value="Jensen">Jensen</option>
<option value="JiaJue">JiaJue</option>
<option value="Jianshe">Jianshe</option>
<option value="KAYAK">KAYAK</option>
<option value="KEEWAY">KEEWAY</option>
<option value="KEHAR">KEHAR</option>
<option value="KIBO">KIBO</option>
<option value="KRONE">KRONE</option>
<option value="KTM">KTM</option>
<option value="KUBOTA">KUBOTA</option>
<option value="Kawasaki">Kawasaki</option>
<option value="Kia">Kia</option>
<option value="Kymco">Kymco</option>
<option value="LDV">LDV</option>
<option value="LIFAN">LIFAN</option>
<option value="LOCAL">LOCAL</option>
<option value="LTI">LTI</option>
<option value="Lada">Lada</option>
<option value="Lamborghini">Lamborghini</option>
<option value="Lancia">Lancia</option>
<option value="Land Rover">Land Rover</option>
<option value="Lexus">Lexus</option>
<option value="Ligier">Ligier</option>
<option value="Lincoln">Lincoln</option>
<option value="Lotus">Lotus</option>
<option value="Luaz">Luaz</option>
<option value="MAN">MAN</option>
<option value="MASSEY">MASSEY</option>
<option value="MCI">MCI</option>
<option value="MEYLUN">MEYLUN</option>
<option value="MG">MG</option>
<option value="MIA">MIA</option>
<option value="MV Agusta">MV Agusta</option>
<option value="Mahindra">Mahindra</option>
<option value="Marcos">Marcos</option>
<option value="Maserati">Maserati</option>
<option value="Maybach">Maybach</option>
<option value="Mazda">Mazda</option>
<option value="Mclaren">Mclaren</option>
<option value="Mega">Mega</option>
<option value="Mercedes">Mercedes</option>
<option value="Mercedes-Benz">Mercedes-Benz</option>
<option value="Mercury">Mercury</option>
<option value="Metrocab">Metrocab</option>
<option value="Microcar">Microcar</option>
<option value="Middlebridge">Middlebridge</option>
<option value="Mini">Mini</option>
<option value="Mitsubishi">Mitsubishi</option>
<option value="Morgan">Morgan</option>
<option value="Morris">Morris</option>
<option value="Moto Guzzi">Moto Guzzi</option>
<option value="NEW HOLLAND">NEW HOLLAND</option>
<option value="NEW T-KING">NEW T-KING</option>
<option value="NOBLE">NOBLE</option>
<option value="NSU">NSU</option>
<option value="Nissan">Nissan</option>
<option value="Oldsmobile">Oldsmobile</option>
<option value="Oltcit">Oltcit</option>
<option value="Opel">Opel</option>
<option value="Osca">Osca</option>
<option value="PGO">PGO</option>
<option value="PIAGGIO">PIAGGIO</option>
<option value="Pagani">Pagani</option>
<option value="Panther">Panther</option>
<option value="Peugeot">Peugeot</option>
<option value="Piaggio">Piaggio</option>
<option value="Pininfarina">Pininfarina</option>
<option value="Plymouth">Plymouth</option>
<option value="Polaris">Polaris</option>
<option value="Pontiac">Pontiac</option>
<option value="Porsche">Porsche</option>
<option value="Premier">Premier</option>
<option value="Proton">Proton</option>
<option value="Puch">Puch</option>
<option value="RANDON TRAILER">RANDON TRAILER</option>
<option value="RIYA">RIYA</option>
<option value="Ranger">Ranger</option>
<option value="Ranger Hunter">Ranger Hunter</option>
<option value="Rayton Fissore">Rayton Fissore</option>
<option value="Reliant">Reliant</option>
<option value="Renault">Renault</option>
<option value="Riley">Riley</option>
<option value="Rolls-Royce">Rolls-Royce</option>
<option value="Romanital">Romanital</option>
<option value="Rover">Rover</option>
<option value="Royal Enfield">Royal Enfield</option>
<option value="SAKAI">SAKAI</option>
<option value="SAN-AGREE">SAN-AGREE</option>
<option value="SCAMELL">SCAMELL</option>
<option value="SCHACMAN">SCHACMAN</option>
<option value="SCHMITZ">SCHMITZ</option>
<option value="SDLG">SDLG</option>
<option value="SHACMAN">SHACMAN</option>
<option value="SHANDONG">SHANDONG</option>
<option value="SHINERAY">SHINERAY</option>
<option value="SINOTRUCK">SINOTRUCK</option>
<option value="SIYAMA">SIYAMA</option>
<option value="SKELETAL">SKELETAL</option>
<option value="SKYGO">SKYGO</option>
<option value="SKYPLEX">SKYPLEX</option>
<option value="STC">STC</option>
<option value="SWM">SWM</option>
<option value="SYM">SYM</option>
<option value="Saab">Saab</option>
<option value="Santana">Santana</option>
<option value="Saturn">Saturn</option>
<option value="Scania">Scania</option>
<option value="Scion">Scion</option>
<option value="Seat">Seat</option>
<option value="Shelby">Shelby</option>
<option value="Sherco">Sherco</option>
<option value="Skoda">Skoda</option>
<option value="Smart">Smart</option>
<option value="Spectre">Spectre</option>
<option value="Spyker">Spyker</option>
<option value="Ssangyong">Ssangyong</option>
<option value="Standard">Standard</option>
<option value="Subaru">Subaru</option>
<option value="Sunbeam">Sunbeam</option>
<option value="Suzuki">Suzuki</option>
<option value="Synergy">Synergy</option>
<option value="TADANO CRANE">TADANO CRANE</option>
<option value="TEREX">TEREX</option>
<option value="TIGER">TIGER</option>
<option value="TITAN TRAILER">TITAN TRAILER</option>
<option value="TOP RICH">TOP RICH</option>
<option value="TRACTOR">TRACTOR</option>
<option value="TRAILER">TRAILER</option>
<option value="TRAILER KING">TRAILER KING</option>
<option value="TRANSTRAILER">TRANSTRAILER</option>
<option value="TVR">TVR</option>
<option value="TVS">TVS</option>
<option value="Talbot">Talbot</option>
<option value="Tata">Tata</option>
<option value="Tesla">Tesla</option>
<option value="Thumpstar">Thumpstar</option>
<option value="Tomcar">Tomcar</option>
<option value="Torino">Torino</option>
<option value="TOYOTA">TOYOTA</option>
<option value="Trabant">Trabant</option>
<option value="Triumph">Triumph</option>
<option value="Triumph">Triumph</option>
<option value="ULTRANAZZ">ULTRANAZZ</option>
<option value="UMM">UMM</option>
<option value="V2COM">V2COM</option>
<option value="VEM">VEM</option>
<option value="VIBERTI">VIBERTI</option>
<option value="VOLKSWAGEN">VOLKSWAGEN</option>
<option value="VW">VW</option>
<option value="Vauxhall">Vauxhall</option>
<option value="Vespa">Vespa</option>
<option value="Victory">Victory</option>
<option value="Victory Auto">Victory Auto</option>
<option value="Vm 77">Vm 77</option>
<option value="Volvo">Volvo</option>
<option value="WUHAN">WUHAN</option>
<option value="Wartburg">Wartburg</option>
<option value="Westfield">Westfield</option>
<option value="Wiesmann">Wiesmann</option>
<option value="Wolseley">Wolseley</option>
<option value="XGMA XG953H">XGMA XG953H</option>
<option value="YATIAN">YATIAN</option>
<option value="YCF">YCF</option>
<option value="YORK">YORK</option>
<option value="Yamaha">Yamaha</option>
<option value="Yugo">Yugo</option>
<option value="Yulon">Yulon</option>



